proxy: extracreditprox.c
	gcc -Wall -o proxy extracreditprox.c
tcpclient: tcp_recv.c
	gcc -Wall -o tcpclient tcp_recv.c
tcpserver: tcp_send.c
	gcc -Wall -o tcpserver tcp_send.c

udpclient: udp_client.c
	gcc -Wall -o udpclient udp_client.c
udpserver: udp_server.c
	gcc -Wall -o udpserver udp_server.c
